// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"webook/article/events"
	"webook/article/grpc"
	"webook/article/ioc"
	"webook/article/repository"
	"webook/article/repository/cache"
	"webook/article/repository/dao"
	"webook/article/service"
)

// Injectors from wire.go:

func initApp() *App {
	loggerV1 := ioc.InitLogger()
	db := ioc.InitDB(loggerV1)
	articleDao := dao.NewGormArticleDao(db)
	client := ioc.InitAliyunOss()
	cmdable := ioc.InitRedis()
	articleCache := cache.NewArticleRedisCache(cmdable)
	articleRepository := repository.NewCachedArticleRepository(articleDao, client, articleCache)
	userServiceClient := ioc.InitUserRpcClient()
	authorRepository := repository.NewGrpcAuthorRepository(articleDao, userServiceClient)
	syncProducer := ioc.InitSyncProducer()
	producer := events.NewKafkaProducer(syncProducer)
	articleService := service.NewArticleService(articleRepository, authorRepository, producer)
	articleServiceServer := grpc.NewArticleServiceServer(articleService)
	clientv3Client := ioc.InitEtcdClient()
	server := ioc.NewGrpcxServer(articleServiceServer, loggerV1, clientv3Client)
	app := &App{
		server: server,
	}
	return app
}

// wire.go:

var serverSet = wire.NewSet(dao.NewGormArticleDao, cache.NewArticleRedisCache, repository.NewCachedArticleRepository, repository.NewGrpcAuthorRepository, service.NewArticleService, grpc.NewArticleServiceServer, events.NewKafkaProducer)

var thirdSet = wire.NewSet(ioc.InitRedis, ioc.InitDB, ioc.InitEtcdClient, ioc.NewGrpcxServer, ioc.InitLogger, ioc.InitAliyunOss, ioc.InitSyncProducer, ioc.InitUserRpcClient)
