// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"webook/payment/grpc"
	"webook/payment/ioc"
	"webook/payment/repository"
	"webook/payment/repository/dao"
	"webook/payment/web"
)

// Injectors from wire.go:

func InitApp() *App {
	wechatConfig := ioc.InitWechatConfig()
	client := ioc.InitWechatClient(wechatConfig)
	loggerV1 := ioc.InitLogger()
	db := ioc.InitDB(loggerV1)
	paymentDAO := dao.NewPaymentGORMDAO(db)
	paymentRepository := repository.NewPaymentRepository(paymentDAO)
	nativePaymentService := ioc.InitWechatNativeService(client, paymentRepository, loggerV1, wechatConfig)
	paymentServiceServer := grpc.NewPaymentServiceServer(nativePaymentService)
	clientv3Client := ioc.NewEtcdClient()
	server := ioc.NewGrpcServer(paymentServiceServer, clientv3Client, loggerV1)
	handler := ioc.InitWechatNotifyHandler(wechatConfig)
	wechatHandler := web.NewWechatHandler(handler, loggerV1, nativePaymentService)
	ginxServer := ioc.NewWebServer(wechatHandler)
	app := &App{
		server: server,
		web:    ginxServer,
	}
	return app
}

// wire.go:

var ServerSet = wire.NewSet(dao.NewPaymentGORMDAO, repository.NewPaymentRepository, web.NewWechatHandler, grpc.NewPaymentServiceServer)

var thirdSet = wire.NewSet(ioc.InitLogger, ioc.NewEtcdClient, ioc.InitDB, ioc.NewGrpcServer)

var wechatSet = wire.NewSet(ioc.InitWechatConfig, ioc.InitWechatNotifyHandler, ioc.InitWechatClient, ioc.InitWechatNativeService)
