// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"webook/search/grpc"
	"webook/search/ioc"
	"webook/search/repository"
	"webook/search/repository/dao"
	"webook/search/service"
)

// Injectors from wire.go:

func initApp() *App {
	client := ioc.InitESClient()
	anyDAO := dao.NewAnyESDAO(client)
	anyRepository := repository.NewAnyRepository(anyDAO)
	userDAO := dao.NewUserElasticDAO(client)
	userRepository := repository.NewUserRepository(userDAO)
	articleDAO := dao.NewArticleElasticDAO(client)
	tagDAO := dao.NewTagESDAO(client)
	articleRepository := repository.NewArticleRepository(articleDAO, tagDAO)
	syncService := service.NewSyncService(anyRepository, userRepository, articleRepository)
	searchSyncServiceServer := grpc.NewSearchSyncServiceServer(syncService)
	searchService := service.NewSearchService(userRepository, articleRepository)
	searchServiceServer := grpc.NewSearchServiceServer(searchService)
	clientv3Client := ioc.InitEtcdClient()
	loggerV1 := ioc.InitLogger()
	server := ioc.InitGRPCxServer(searchSyncServiceServer, searchServiceServer, clientv3Client, loggerV1)
	app := &App{
		server: server,
	}
	return app
}

// wire.go:

var serverSet = wire.NewSet(dao.NewArticleElasticDAO, dao.NewAnyESDAO, dao.NewTagESDAO, dao.NewUserElasticDAO, repository.NewAnyRepository, repository.NewArticleRepository, repository.NewUserRepository, service.NewSearchService, service.NewSyncService, grpc.NewSearchSyncServiceServer, grpc.NewSearchServiceServer)

var thirdSet = wire.NewSet(ioc.InitLogger, ioc.InitESClient, ioc.InitGRPCxServer, ioc.InitEtcdClient)
