// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"webook/code/grpc"
	"webook/code/ioc"
	"webook/code/repository"
	"webook/code/repository/cache"
	"webook/code/service"
)

// Injectors from wire.go:

func initApp() *App {
	cmdable := ioc.InitRedis()
	codeCache := cache.NewCodeCache(cmdable)
	codeRepository := repository.NewCodeRepository(codeCache)
	client := ioc.InitEtcdClient()
	smsServiceClient := ioc.InitSmsGRPCClient(client)
	codeService := service.NewCodeService(codeRepository, smsServiceClient)
	codeServiceServer := grpc.NewCodeServiceServer(codeService)
	loggerV1 := ioc.InitLogger()
	server := ioc.NewGrpcxServer(codeServiceServer, loggerV1, client)
	app := &App{
		server: server,
	}
	return app
}

// wire.go:

var serverSet = wire.NewSet(cache.NewCodeCache, repository.NewCodeRepository, service.NewCodeService, grpc.NewCodeServiceServer)

var thirdSet = wire.NewSet(ioc.InitRedis, ioc.InitEtcdClient, ioc.InitLogger, ioc.NewGrpcxServer)

var clientSet = wire.NewSet(ioc.InitSmsGRPCClient)
