// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/DaHuangQwQ/webook/account/grpc"
	"github.com/DaHuangQwQ/webook/account/ioc"
	"github.com/DaHuangQwQ/webook/account/repository"
	"github.com/DaHuangQwQ/webook/account/repository/dao"
	"github.com/DaHuangQwQ/webook/account/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

func initApp() *App {
	client := ioc.NewEtcdClient()
	loggerV1 := ioc.InitLogger()
	db := ioc.InitDB(loggerV1)
	accountDAO := dao.NewAccountGORMDAO(db)
	accountRepository := repository.NewAccountRepository(accountDAO)
	accountService := service.NewAccountService(accountRepository)
	accountServiceServer := grpc.NewAccountServiceServer(accountService)
	server := ioc.NewGrpcServer(client, loggerV1, accountServiceServer)
	app := &App{
		server: server,
	}
	return app
}

// wire.go:

var serverSet = wire.NewSet(dao.NewAccountGORMDAO, repository.NewAccountRepository, service.NewAccountService, grpc.NewAccountServiceServer)

var thirdSet = wire.NewSet(ioc.InitDB, ioc.InitLogger, ioc.NewEtcdClient, ioc.NewGrpcServer)
