// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/DaHuangQwQ/webook/follow/grpc"
	"github.com/DaHuangQwQ/webook/follow/ioc"
	"github.com/DaHuangQwQ/webook/follow/repository"
	"github.com/DaHuangQwQ/webook/follow/repository/cache"
	"github.com/DaHuangQwQ/webook/follow/repository/dao"
	"github.com/DaHuangQwQ/webook/follow/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

func initApp() *App {
	loggerV1 := ioc.InitLogger()
	db := ioc.InitDB(loggerV1)
	followRelationDao := dao.NewGORMFollowRelationDAO(db)
	cmdable := ioc.InitRedis()
	followCache := cache.NewRedisFollowCache(cmdable)
	followRepository := repository.NewFollowRelationRepository(followRelationDao, followCache, loggerV1)
	followRelationService := service.NewFollowRelationService(followRepository)
	followServiceServer := grpc.NewFollowServiceServer(followRelationService)
	client := ioc.InitEtcdClient()
	server := ioc.NewGrpcServer(followServiceServer, client, loggerV1)
	app := &App{
		server: server,
	}
	return app
}

// wire.go:

var serverSet = wire.NewSet(cache.NewRedisFollowCache, dao.NewGORMFollowRelationDAO, repository.NewFollowRelationRepository, service.NewFollowRelationService, grpc.NewFollowServiceServer)

var thirdSet = wire.NewSet(ioc.InitRedis, ioc.InitDB, ioc.InitLogger, ioc.InitEtcdClient, ioc.NewGrpcServer)
