// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/DaHuangQwQ/webook/user/grpc"
	"github.com/DaHuangQwQ/webook/user/ioc"
	"github.com/DaHuangQwQ/webook/user/repository"
	"github.com/DaHuangQwQ/webook/user/repository/cache"
	"github.com/DaHuangQwQ/webook/user/repository/dao"
	"github.com/DaHuangQwQ/webook/user/repository/system"
	"github.com/DaHuangQwQ/webook/user/service"
	system2 "github.com/DaHuangQwQ/webook/user/service/system"
	"github.com/DaHuangQwQ/webook/user/web"
	"github.com/google/wire"
)

// Injectors from wire.go:

func initApp() *App {
	loggerV1 := ioc.InitLogger()
	db := ioc.InitDB(loggerV1)
	userDao := dao.NewUserDao(db)
	cmdable := ioc.InitRedis()
	userCache := cache.NewUserCache(cmdable)
	client := ioc.InitOssService()
	userRepository := repository.NewUserRepository(userDao, userCache, client)
	userService := service.NewUserService(userRepository)
	userServiceServer := grpc.NewUserServiceServer(userService)
	clientv3Client := ioc.InitEtcdClient()
	server := ioc.NewGrpcxServer(userServiceServer, loggerV1, clientv3Client)
	v := ioc.InitGinMiddlewares(cmdable)
	authDao := dao.NewGormAuthDao(db)
	iEnforcer := ioc.InitCasbinService()
	authRepository := system.NewCachedAuthRepository(authDao, iEnforcer)
	authService := system2.NewAuthService(authRepository)
	roleDao := dao.NewGormRoleDao(db)
	roleRepository := system.NewCachedRoleRepository(iEnforcer, roleDao)
	roleService := system2.NewRoleService(roleRepository, authRepository)
	authHandler := web.NewAuthHandler(authService, loggerV1, roleService)
	roleHandler := web.NewRoleHandler(roleService, loggerV1)
	systemUserRepository := system.NewCachedUserRepository(iEnforcer, userDao)
	deptDao := dao.NewGormDeptDao(db)
	deptRepository := system.NewCachedDeptRepository(deptDao)
	deptService := system2.NewDeptService(deptRepository)
	systemUserService := system2.NewSystemService(roleService, authService, systemUserRepository, deptService)
	userHandler := web.NewUserHandler(systemUserService, loggerV1)
	deptHandler := web.NewDeptHandler(deptService, loggerV1)
	monitorService := system2.NewSysMonitorService()
	monitorHandler := web.NewMonitorHandler(monitorService)
	ginxServer := ioc.InitWebServer(v, authHandler, roleHandler, userHandler, deptHandler, monitorHandler)
	app := &App{
		server:   server,
		webAdmin: ginxServer,
	}
	return app
}

// wire.go:

var serverSet = wire.NewSet(dao.NewUserDao, cache.NewUserCache, repository.NewUserRepository, service.NewUserService, grpc.NewUserServiceServer)

var thirdSet = wire.NewSet(ioc.InitLogger, ioc.InitDB, ioc.InitRedis, ioc.InitOssService, ioc.InitCasbinService, ioc.InitEtcdClient, ioc.NewGrpcxServer)
