// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/DaHuangQwQ/webook/tag/events"
	"github.com/DaHuangQwQ/webook/tag/grpc"
	"github.com/DaHuangQwQ/webook/tag/ioc"
	"github.com/DaHuangQwQ/webook/tag/repository"
	"github.com/DaHuangQwQ/webook/tag/repository/cache"
	"github.com/DaHuangQwQ/webook/tag/repository/dao"
	"github.com/DaHuangQwQ/webook/tag/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

func initApp() *App {
	loggerV1 := ioc.InitLogger()
	db := ioc.InitDB(loggerV1)
	tagDAO := dao.NewGORMTagDAO(db)
	cmdable := ioc.InitRedis()
	tagCache := cache.NewRedisTagCache(cmdable)
	tagRepository := repository.NewTagRepository(tagDAO, tagCache, loggerV1)
	client := ioc.InitKafka()
	syncProducer := ioc.InitSyncProducer(client)
	producer := events.NewSaramaSyncProducer(syncProducer)
	tagService := service.NewTagService(tagRepository, producer, loggerV1)
	tagServiceServer := grpc.NewTagServiceServer(tagService)
	clientv3Client := ioc.InitEtcdClient()
	server := ioc.NewGrpcxServer(tagServiceServer, loggerV1, clientv3Client)
	app := &App{
		server: server,
	}
	return app
}

// wire.go:

var serverSet = wire.NewSet(cache.NewRedisTagCache, dao.NewGORMTagDAO, repository.NewTagRepository, service.NewTagService, grpc.NewTagServiceServer, events.NewSaramaSyncProducer)

var thirdSet = wire.NewSet(ioc.InitLogger, ioc.InitDB, ioc.InitRedis, ioc.InitEtcdClient, ioc.NewGrpcxServer, ioc.InitKafka, ioc.InitSyncProducer)
